site_name: prefect-hightouch
site_url: https://PrefectHQ.github.io/prefect-hightouch
repo_url: https://github.com/PrefectHQ/prefect-hightouch
edit_uri: edit/main/docs/
theme:
  name: material
  favicon: img/favicon.ico
  palette:
    primary: blue
    accent: blue
  icon:
    repo: fontawesome/brands/github
  logo:
    img/prefect-logo-mark-solid-white-500.png
  font:
    text: Inter
    code: Source Code Pro
extra_css:
    - stylesheets/extra.css
markdown_extensions:
    - admonition
    - attr_list
    - codehilite
    - md_in_html
    - meta
    - pymdownx.highlight:
        use_pygments: true
    - pymdownx.superfences
    - pymdownx.tabbed
plugins:
  - search
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - mkdocstrings:
      handlers:
        python:
          options:
            show_submodules: True
            show_root_heading: True
            show_object_full_path: False
            show_category_heading: False
            show_bases: True
            show_signature: False
            heading_level: 1
            filters: ["!^__[^__]", "!T", "!Response"]

watch:
    - prefect_hightouch/
    - README.md

nav:
    - Home: index.md
    - Syncs: syncs.md
    - Credentials: credentials.md
    - Exceptions: exceptions.md
    
    - API Models:
        - Sync: models/sync.md
        - ListSyncResponse200: models/list_sync_response_200.md
        - CronSchedule: models/cron_schedule.md
        - ValidateErrorJsonMessage: models/validate_error_json_message.md
        - ListModelResponse200: models/list_model_response_200.md
        - TriggerRunInput: models/trigger_run_input.md
        - ModelDbt: models/model_dbt.md
        - ModelCustom: models/model_custom.md
        - ModelRaw: models/model_raw.md
        - RecordDayBooleanOrUndefined: models/record_day_boolean_or_undefined.md
        - Destination: models/destination.md
        - SyncRun: models/sync_run.md
        - IntervalUnit: models/interval_unit.md
        - Interval: models/interval.md
        - SyncRunPlannedRows: models/sync_run_planned_rows.md
        - ListSyncOrderBy: models/list_sync_order_by.md
        - ListModelOrderBy: models/list_model_order_by.md
        - ValidateErrorJson: models/validate_error_json.md
        - ModelTable: models/model_table.md
        - ListSyncRunsOrderBy: models/list_sync_runs_order_by.md
        - ModelTags: models/model_tags.md
        - DbtScheduleJob: models/dbt_schedule_job.md
        - SyncStatus: models/sync_status.md
        - DbtSchedule: models/dbt_schedule.md
        - TriggerRunCustomInput: models/trigger_run_custom_input.md
        - SyncRunStatus: models/sync_run_status.md
        - TriggerRunOutput: models/trigger_run_output.md
        - Model: models/model.md
        - SyncRunFailedRows: models/sync_run_failed_rows.md
        - ListDestinationOrderBy: models/list_destination_order_by.md
        - SyncSchedule: models/sync_schedule.md
        - ListSyncRunsResponse200: models/list_sync_runs_response_200.md
        - SyncRunSuccessfulRows: models/sync_run_successful_rows.md
        - ListSourceResponse200: models/list_source_response_200.md
        - ModelVisual: models/model_visual.md
        - VisualCronSchedule: models/visual_cron_schedule.md
        - DestinationConfiguration: models/destination_configuration.md
        - VisualCronScheduleExpressionsItem: models/visual_cron_schedule_expressions_item.md
        - SyncConfiguration: models/sync_configuration.md
        - IntervalSchedule: models/interval_schedule.md
        - ListDestinationResponse200: models/list_destination_response_200.md
        - ValidateErrorJsonDetails: models/validate_error_json_details.md
        - Source: models/source.md
        - DbtScheduleAccount: models/dbt_schedule_account.md
        - SourceConfiguration: models/source_configuration.md
        - ListSourceOrderBy: models/list_source_order_by.md
    
    - API Endpoints:
        - get_destination: endpoints/get_destination.md
        - get_source: endpoints/get_source.md
        - list_model: endpoints/list_model.md
        - trigger_run_custom: endpoints/trigger_run_custom.md
        - list_source: endpoints/list_source.md
        - trigger_run: endpoints/trigger_run.md
        - get_sync: endpoints/get_sync.md
        - get_model: endpoints/get_model.md
        - list_sync: endpoints/list_sync.md
        - list_destination: endpoints/list_destination.md
        - list_sync_runs: endpoints/list_sync_runs.md
